server:
  port: 8081

spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/ecommercedb
    username: dev_user 
    password: dev_pass
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect 
  mvc: 
    cors: 
      mappings: 
        - path-pattern: /api/** 
          allowed-origins: "http://localhost:3000" 
          allowed-methods: "GET,POST,PUT,PATCH,DELETE" 
          allowed-headers: "*" 
          allow-credentials: true 

 
 
jwt: 
  secret: "replace-with-256-bit-secret" 
  issuer: "ecommerce-dev" 
  expiry-minutes: 60